### ISSUE TITLE
Unable to build in poudriere

### ISSUE THREAD

**Issue by CyberBotX** [tagattie/FreeBSD-VSCode#10]
While the pre-built package seems to work perfectly fine, I was wanting to build it on my own poudriere instance. However, it does not build for me. Ultimately what I get is:
```
Error: EMFILE: too many open files, open '/wrkdirs/usr/ports/editors/vscode/work/vscode-1.38.1/out-build/vs/workbench/services/textMate/common/TMScopeRegistry.js.map'
```
Full build log from poudriere can be found here: http://kirby.cyberbotx.com:8765/poudriere/data/local-default/2019-10-21_20h28m47s/logs/errors/vscode-1.38.1.log

I don't know where the fault is in this case. It is possible it might be my system configuration, but I can't say for sure. I have the following in sysctl:
```
kern.maxfiles: 2091974
kern.maxfilesperproc: 1882773
```

**Comment by CyberBotX** [comment]
So, I'm going to close this, it turns out that poudriere uses its own resource limits and not what the host has in its sysctl. I upped the max files limit in poudriere.conf and that allowed me to build the port.

**Comment by amiramix** [comment]
I just stumbled upon this as well. Is there any recommended limit for building VSCode in poudriere? How much did you put in poudriere.conf?

**Comment by tagattie** [comment]
Can you check the following URL? It describes the necessary configuration of poudriere to build vscode.
https://github.com/tagattie/FreeBSD-VSCode#note-for-poudriere-users
