### ISSUE TITLE
No cotext menu for a file

### ISSUE THREAD

**Issue by basarevych** [tagattie/FreeBSD-VSCode#13]
When I right-click the left pane with files nothing happens (no file context menu). It's been like this several releases already. Am I the only one?

**Comment by tagattie** [comment]
Hi @basarevych,

Thanks for reporting the issue.
You are not alone. I have the same problem with vers 1.40.1 and 1.40.2.
Ver 1.39.2 seems OK.

I will look into the problem.

**Comment by tagattie** [comment]
It appears the problem was due to a missing patch in `devel/electron6` port.
I will re-upload VSCode packages with patched electron6 in a few days.

**Comment by basarevych** [comment]
Thank you very much!

**Comment by tagattie** [comment]
I've just uploaded updated package files (ver 1.40.2). Can you try and see if it's OK?

**Comment by lapo-luchini** [comment]
It works for me (with the new package)!

**Comment by basarevych** [comment]
Context menu works now. Thank you.
