### ISSUE TITLE
Cannot find name 'AsyncIterator'. / esnext.asynciterable / es2018

### ISSUE THREAD

**Issue by jsm222** [tagattie/FreeBSD-VSCode#14]
../../../../../../../node_modules/@types/graphql/subscription/subscribe.d.ts:17:4 - error TS2304: Cannot find name 'AsyncIterator'.

17 ): AsyncIterator<ExecutionResult>;
      ~~~~~~~~~~~~~


../../../../../../../node_modules/@types/graphql/subscription/subscribe.d.ts:29:4 - error TS2304: Cannot find name 'AsyncIterable'.

29 ): AsyncIterable<any>;
      ~~~~~~~~~~~~~

I'm not sure if changing to es2018 would fix it or be more correct.
But the tests needs asynciterable
test/smoke/tsconfig.json
```diff
@@ -12,6 +12,7 @@
                "sourceMap": true,
                "lib": [
                        "es2016",
+                       "esnext.asynciterable",
                        "dom"
                ]
        },
```
test/automation/tsconfig.json
```diff
@@ -10,6 +10,7 @@
                "declaration": true,
                "lib": [
                        "es2016",
+                       "esnext.asynciterable",
                        "dom"
                ]
        },
```

**Comment by tagattie** [comment]
I can't seem to reproduce the error. Does the error occur with the latest version of the port (1.41.0) too?

With 1.41.0, there is no directory named `graphql` under vscode source directory.

**Comment by jsm222** [comment]
Have not looked deeper into it, but perhaps just a thing local on my machine
