### ISSUE TITLE
C/C++ workflow / Debugging

### ISSUE THREAD

**Issue by kusius** [tagattie/FreeBSD-VSCode#15]
Hello! First of all, huge thanks for this effort youre doing here.

Ive been trying to use code as a debugger for C/C++ executables by installing the extension. I wanted to ask if, first of all this extension is supposed to even work in our case, or do i need to build the extension specifically for freebsd.

I can provide you with the launch.json if you want, but basically what i get is a `convertToDto unexpected type`  error. The type ive set in the launch.json is `cppdbg`

**Comment by tagattie** [comment]
I don't use the C/C++ extension. So this may be wrong.

The extension appears to depend on some platform-specific binaries (`Microsoft.VSCode.CPP.Extension.linux` and `Microsoft.VSCode.CPP.IntelliSense.Msvc.linux`), which are not open source.

Notes (though it is outdated) at the following URL describe how you can use the extension with FreeBSD's linux binary compatibility functions:
https://github.com/prash-wghats/Electron-VSCode-Atom-For-FreeBSD/blob/master/vscode/Readme.md#vscode-1172

**Comment by tagattie** [comment]
At least, you need to download and install an "offline vsix" from github releases page instead of installing from the marketplace. The offline vsix includes those platform-specific binaries.

https://github.com/microsoft/vscode-cpptools/releases
