### ISSUE TITLE
Git push not working

### ISSUE THREAD

**Issue by basarevych** [tagattie/FreeBSD-VSCode#16]
When I switch to the git pane, commit the changes and choose "push" from the menu, an indicator starts moving, but nothing else happens.

This repo requires credentials, and back when it was working some releases ago, I remember that a little popup appeared asking for the credentials. Which is not happening in the current version.

Could you please look into it?

**Comment by tagattie** [comment]
`git push` is working here.

Can you choose "Show Git Output" from the three-dots menu and see if there are any errors displayed with git command execution?

**Comment by basarevych** [comment]
Nothing suspicious there. Ends with:

```
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git rev-parse --show-toplevel
> git push origin master:master
```
According to this https://github.com/microsoft/vscode/blob/master/extensions/git/src/askpass.ts VSCode overrides GIT_ASKPASS environment variable with its own script and creates a window. However, I do not see that window appearing...

Tried removing all VSCODE config directories from home, but it still hangs on push...

**Comment by tagattie** [comment]
The error appears due to a wrong permission of askpass scripts.
Can you do the following and see if the error goes away?

```
cd /usr/local/share/code-oss/resources/app/extensions/git/dist
sudo chmod +x askpass.sh askpass-empty.sh
```

I will fix the problem in the next release of package.

**Comment by basarevych** [comment]
It works now. Thank you very much!
