### ISSUE TITLE
No vscode package in pkg

### ISSUE THREAD

**Issue by DesantBucie** [tagattie/FreeBSD-VSCode#28]
Hey.
I'm running FreeBSD12.1R and **latest** pkg mirror. Does you package only exist in **quarterly** mirror?
`pkg install vscode` and `pkg search vscode` doesn't give anything.

**Comment by lapo-luchini** [comment]
You can verify the [availability matrix](https://www.freshports.org/editors/vscode/) on Freshports.
It does indeed to be missing on _latest_ FreeBSD-12/amd64 (while is present on _latest_ FreeBSD-13/amd64).
(As the reason why, I don't know.)

**Comment by DesantBucie** [comment]
Ah thanks, didn't see that table. Well I guess i will have to build it or go back to quarterly.

**Comment by grahamperrin** [comment]
There's now an anchor within the page: 

<https://www.freshports.org/editors/vscode/#packages>

Packages are currently available for `FreeBSD:13:amd64` (latest and quarterly) `and FreeBSD:14:amd64` (latest). 

@DesantBucie assuming that you have upgrade to FreeBSD 13.0-RELEASE, would you like to close this issue? 

Thanks. 

----

Reasons for absences can be found via <https://pkg-status.freebsd.org/builds?type=package>, for example: 

* http://beefy6.nyi.freebsd.org/jail.html?mastername=122amd64-default ▶ latest build

At the time of writing: 

![image](https://user-images.githubusercontent.com/192271/140640620-c13dd6ad-b3bd-4e6d-a810-1480e026e976.png)

**Comment by DesantBucie** [comment]
Yes sorry, totally forgot to do so year ago.
