### ISSUE TITLE
Update 1.50.2 ?

### ISSUE THREAD

**Issue by drupol** [tagattie/FreeBSD-VSCode#30]
Hi there,

Are there any plan to upgrade to 1.50.1 ?

Thanks!

**Comment by goyox86** [comment]
Hi! Awesome port! I am also interested in the latest version so I can run rust-analizer. 

If you are willing to mentor I can try to update the port!

Cheers

**Comment by drupol** [comment]
Dear @tagattie,

Do you plan to maintain this port or you need some help?

Thanks!

**Comment by drupol** [comment]
Thanks !!!

Closing the issue now :-)
