### ISSUE TITLE
Codium package?

### ISSUE THREAD

**Issue by drupol** [tagattie/FreeBSD-VSCode#32]
Dear @tagattie,

I'm using your package VSCode everyday on FreeBSD and I thank you.

However, most of my friends and colleagues are using [VSCodium](https://vscodium.com/).

Codium is a community-driven, freely-licensed binary distribution of Microsoft’s editor VSCode.

Basically, VSCodium is VSCode without the Microsoft Telemetry.

Do you plan to make such a package for FreeBSD?

Thanks!

**Comment by tagattie** [comment]
Currently I don't plan to port VSCodium.

You can disable telemetry reporting in VSCode by following the instruction at:
https://code.visualstudio.com/docs/getstarted/telemetry#_disable-telemetry-reporting
