### ISSUE TITLE
Update to 1.61.2 …

### ISSUE THREAD

**Issue by grahamperrin** [tagattie/FreeBSD-VSCode#35]
https://github.com/tagattie/FreeBSD-VSCode/commit/a44d1c7c508b59f506d79aef07544ca36fc5f62a for `1.56.2` noted with thanks. 

https://github.com/microsoft/vscode/issues/136409#issuecomment-960547873 enquires about `1.61.2`. 

Please: is an issue (here) appropriate? 

Or better to raise it in the FreeBSD area? (To appear amongst [search results for editors/vscode](https://bugs.freebsd.org/bugzilla/buglist.cgi?component=Individual%20Port%28s%29&list_id=449186&product=Ports%20%26%20Packages&query_format=advanced&resolution=---&short_desc=editors%2Fvscode&short_desc_type=allwordssubstr).)

**Comment by tagattie** [comment]
I plan to update the port to the latest version (1.62.2) in a couple of weeks. So stay tuned...

**Comment by tagattie** [comment]
I have just update the vscode port to 1.62.3. Please give it a try.

**Comment by grahamperrin** [comment]
Thanks! 

As a minimal test, 1.62.3 does start on 13.0-RELEASE-p4 in a test machine (using VirtualBox): 

```text
freebsd@freebsd:/usr/home/freebsd $ vscode
freebsd@freebsd:/usr/home/freebsd $ which vscode
/usr/local/bin/vscode
freebsd@freebsd:/usr/home/freebsd $ pkg info -x vscode
vscode-1.62.3
freebsd@freebsd:/usr/home/freebsd $ uname -aKU
FreeBSD freebsd 13.0-RELEASE-p4 FreeBSD 13.0-RELEASE-p4 #0: Tue Aug 24 07:33:27 UTC 2021     root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64 1300139 1300139
freebsd@freebsd:/usr/home/freebsd $ freebsd-version -kru
13.0-RELEASE-p4
13.0-RELEASE-p4
13.0-RELEASE-p5
freebsd@freebsd:/usr/home/freebsd $ 
```

For my everyday system – FreeBSD 14.0-CURRENT – I'll: 

1. await availability of the package
2. update my installation, then review https://github.com/microsoft/vscode/issues/136409

<https://www.freshports.org/editors/vscode/#packages> not yet available for `FreeBSD:14:amd64`. In the meantime, via <https://pkg-status.freebsd.org/builds?type=package&jailname=main-amd64&all=1> I see a build success at <http://beefy18.nyi.freebsd.org/build.html?mastername=main-amd64-default&build=pedabbf820119_s3ede04c78c>.
