### ISSUE TITLE
yarn and npm node dependency

### ISSUE THREAD

**Issue by pizzamig** [tagattie/FreeBSD-VSCode#4]
in the BUILD_DEPENDS there is npm-node10, that require node10, and yarn that require node (the last one)
If I manually install npm-node10 and then yarn, those ports will be in conflict (node and node10 will install `bin/node` in the same pathname) so it doesn't work.
Do you want a yarn-node10 as well to solve the issue?
I maintain yarn and I can do it to mimic npm behavior

**Comment by tagattie** [comment]
> Do you want a yarn-node10 as well to solve the issue?

Yes, I was going to file a PR to create slave port `yarn-node10` and `yarn-node8` which use the current LTS versions of node.

> I maintain yarn and I can do it to mimic npm behavior

If you create yarn port with node LTS, I will be more than happy :smile:

**Comment by tagattie** [comment]
Thanks @pizzamig for creating `yarn-node10` and `yarn-node8`! I'm closing this issue.

Now only one thing[1] is blocking VS Code port from becoming poudriere-compatible.

[1] https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=238243

**Comment by pizzamig** [comment]
cool! sunpoet should reply soon.
If not, when the maintainer timeout expires (2 weeks minimum), I can commit it on his behalf.
