### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by dcschmid** [tagattie/FreeBSD-VSCode#5]
Hi,
i try to run vscode on my freebsd pc. I get the following error:
$ ld-elf.so.1: Shared object "libopenh264.so.4" not found, required by "code-oss"
What package i need to install?

Thank you very much.

**Comment by lapo-luchini** [comment]
`/usr/local/lib/libopenh264.so.4 was installed by package openh264-1.8.0,2`
But at least [the 1.35.0 release](https://github.com/tagattie/FreeBSD-VSCode/releases/tag/1.35.0.g20190517) that I'm still using has that as a dependency, so it shouldn't happen.

**Comment by dcschmid** [comment]
Hi lapo,

i install the openh264 package, but the errow was thrown again :-(.

**Comment by tagattie** [comment]
Hi @dcschmid,

Thanks for reporting this issue.

The error appears to be due to the recent version bump of openh264 port. With this bump, the shared library version is update to `.so.4` to `.so.5`. So if you have the latest version of openh264, you will get the error message.

I will re-upload packages (which are linked with `.so.5` of openh264) in a few days.

**Comment by lapo-luchini** [comment]
Thanks for the head-up, I won't update my system either until then. ;)

I was wondering: will VSCode eventually be able to link against the Electron4 port, or does it need a customized Electron (like I think it is now)?

**Comment by tagattie** [comment]
I have uploaded new packages. Can you try again with the ones?

**Comment by dcschmid** [comment]
I will try it when i am home :-)

**Comment by dcschmid** [comment]
Thank you very much. Now its work and i hope it will be one day an  official package. :-)

**Comment by petr-fischer** [comment]
> I have uploaded new packages. Can you try again with the ones?

New packages are OK, tested.

**Comment by pouya-eghbali** [comment]
Chromium installed using pkg needs openh264-1.8 and upgrading to -2.0 causes issues with Chromium, however simply making a link from .so.4 to .so.5 seems to solve the issue.

**Comment by dcschmid** [comment]
Hi all,
when i was try to build it with poudriere i get the following error, how can i solved it.

[02:10:23] 'vscode-linux-x64-min' errored after 2.68 min
[02:10:23] Error: EMFILE: too many open files, open '/wrkdirs/usr/ports/editors/vscode/work/vscode-81d7885dc2e9dc617e1522697a2966bc4025a45d/out-build/vs/workbench/services/keybinding/common/keybindingEditing.js.map'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
*** Error code 1

**Comment by tagattie** [comment]
Check the result of `ulimit -n`. Increasing this value may help.

Mine (on which machine build succeeds) is:
```shell-session
$ ulimit -n
234801
```

**Comment by tagattie** [comment]
> when i was try to build it with poudriere i get the following error, how can i solved it.

The error during build with poudriere is due to the limitation on the max number of files (default is 1024). To avoid the error, add the following line to your `poudriere.conf`:
```
MAX_FILES_vscode=4096
```

**Comment by grahamperrin** [comment]
@dcschmid 

> Now its work

Thank you, would you like to close this issue?
