### ISSUE TITLE
Run code-oss error.

### ISSUE THREAD

**Issue by TokenRanOut** [tagattie/FreeBSD-VSCode#8]
I install vscode-1.37.1-freebsd12-amd64.txz success.
But can't run:
```shell
$ code-oss
ld-elf.so.1: /usr/local/lib/libavutil.so.56: version LIBAVUTIL_56 required by /usr/local/share/code-oss/bin/../code-oss not defined
```
libavutil in my system:
```shell
$ ls /usr/local/lib/libavutil*     
/usr/local/lib/libavutil.a            /usr/local/lib/libavutil.so.56
/usr/local/lib/libavutil.so           /usr/local/lib/libavutil.so.56.22.100
```

My system version: amd64 FreeBSD 12.0-RELEASE-p9.

**Comment by lapo-luchini** [comment]
Works for me on same platform, with following:
`/usr/local/lib/libavutil.so.56.31.100 was installed by package ffmpeg-4.2_1,1`

**Comment by MangyCoyote** [comment]
I experience the very same issue as @PlayByMyself.
Seems like the package has been compiled against newer Port lib(s) version(s) or so?

ffmpeg currently is at 4.1.4_1,1 version (latest stable using pkg).
/usr/local/lib/libavutil.so.56.22.100 is the latest/stable one.

**Comment by tagattie** [comment]
The packages on Releases page are compiled with the port tree with "latest" branch. So please update your `/etc/pkg/FreeBSD.conf` accordingly. (`quarterly` -> `latest`)

The latest branch has `ffmpeg-4.2_1,1` package as pointed out by @lapo-luchini.

**Comment by MangyCoyote** [comment]
Ok, that seems like some sort of a development branch as I understand. I do not want to take a step there from mine FreeBSD 12.0-RELEASE-p10 .
Out of curiosity, I tried and installed on the system version [targeted for 11.0 release](https://github.com/tagattie/FreeBSD-VSCode/releases/download/1.37.1/vscode-1.37.1-freebsd11-amd64.txz) . Application has opened. Not sure about functionaly and features though.

**Comment by TokenRanOut** [comment]
It works,thanks a lot!
@lapo-luchini @tagattie
