### ISSUE TITLE
ld-elf.so.1: /usr/local/lib/libavutil.so.56: version LIBAVUTIL_56 required by /usr/local/share/code-oss/bin/../code-oss not defined

### ISSUE THREAD

**Issue by acarteas** [tagattie/FreeBSD-VSCode#9]
I'm getting an error stating the library can't be found when launching code-oss.  However, doing an ls at /usr/local/lib/ reveals libavutil.so, libavutil.so.56, and libavutil.so.56.22.100.  Any ideas?  This is on 12.0-RELEASE-p10.  

Thanks!

**Comment by tagattie** [comment]
I guess this is a duplicate of #8. Can you take a look to see if the problem can be solved?

**Comment by acarteas** [comment]
Yes, very likely.  Sorry I missed that.
